In [ ]:
# For use with Google Drive
from google.colab import drive
drive.mount('/content/drive')
%cd /content/drive/'My Drive'/'Colab Notebooks'/Hierarchical_HAR-PBD

In [1]:
from Baseline.HierarchicalHAR_PBD import build_model
import Baseline.utils as utils
import numpy as np
from collections import Counter
import h5py
import os
import tensorflow as tf
import keras
tf.keras.utils.set_random_seed(42) # Sets it for TF, numpy and base Python
from tensorflow.keras.layers import * # for the new versions of Tensorflow, layers, models, regularizers, and optimizers shall be imported from Tensorflow.
from tensorflow.keras.models import *
from tensorflow.keras.regularizers import *
from tensorflow.keras.optimizers import *
from keras.losses import * # and losses, metrics, callbacks, and backend can still be used from Keras directly.
from keras.metrics import *
from keras import metrics
from sklearn.metrics import *
from keras import backend as K
from keras.backend import *
from sklearn.model_selection import StratifiedKFold
from keras.callbacks import EarlyStopping
from keras.callbacks import TensorBoard
from numpy.linalg import inv
from scipy.linalg import fractional_matrix_power
from keras.utils.np_utils import *
from keras.models import load_model
from sklearn.metrics import confusion_matrix, f1_score, precision_score, recall_score,accuracy_score
from sklearn import metrics
import seaborn as sns
import pandas as pd
import json
import matplotlib.pyplot as plt

adjacency_matrix = np.zeros((4, 4))
adjacency_matrix[0, 1] = 1
adjacency_matrix[1, 0] = 1
adjacency_matrix[1, 2] = 1
adjacency_matrix[1, 3] = 1
adjacency_matrix[2, 1] = 1
adjacency_matrix[2, 3] = 1
adjacency_matrix[3, 1] = 1
adjacency_matrix[3, 2] = 1
print("Adjacency matrix: ", adjacency_matrix)
norm_adj = utils.MakeGraph(adjacency_matrix)

class HAR_model_wrapper():
    "A class to hold a HAR model and its important properties"
    timestep = 0
    node_num = 0
    feature_num = 0
    adjacency_matrix = None
    num_classes = 0
    def __init__(self, adjacency_matrix, timestep, node_num, feature_num, num_class_HAR=26):
        assert adjacency_matrix.shape[0] == node_num
        assert adjacency_matrix.shape[1] == node_num
        self.model = build_model(timestep=timestep, body_num=node_num, feature_dim=feature_num,
                              gcn_units_HAR=26, lstm_units_HAR=24, adjacency_matrix=adjacency_matrix,
                              gcn_units_PBD=16, lstm_units_PBD=24,
                              num_class_HAR=num_class_HAR, num_class_PBD=2)[1]
        self.num_classes = num_class_HAR
        self.timestep = timestep
        self.node_num = node_num
        self.feature_num = feature_num
        self.adjacency_matrix = adjacency_matrix

X_train = np.load("Data/X_train_pain.npy")
Y_train = np.load("Data/Y_train_pain.npy")
X_test = np.load("Data/X_test_pain.npy")
Y_test = np.load("Data/Y_test_pain.npy")
# Do not use the merge functions if you use this function
# This function also implements merge option 1
def new_encoding(arr: np.ndarray):
    conversion_dict = {1: 1, 2:2, 3:3, 4:4, 5:5, 6:6, 7:7,
                       9:8, 11:8, 14:9, 17:10, 18:11, 20:8,
                       21:12, 22:13, 23:14, 24:15, 25:16, 26:17, 27:18}
    for i in range(arr.shape[0]):
        arr[i][0] = conversion_dict[arr[i][0]]
print("Classes before new encoding ", np.unique(Y_train))
new_encoding(Y_train)
new_encoding(Y_test)
print("Classes after new encoding ", np.unique(Y_train))
result = np.matmul(norm_adj, X_train[0, 0, :, :])
# print("Result of matrix multiplication of normalized adjacency matrix with "
#       "4x3 matrix from X[0, 0]: ", result,
#       "and its shape: ", result.shape)

#Tensorflow expects classes to start from 0, otherwise it throws a fit
Y_train = Y_train - 1
Y_test = Y_test - 1
print("Classes in Y_train: ", np.unique(Y_train))

class_counts = np.unique(Y_train, return_counts=True)
# Add missing labels to class_counts
def add_missing_labels(class_counts: tuple) -> tuple:
    labels = class_counts[0]
    counts = class_counts[1]
    new_labels = np.array(list(range(0, 26)))
    # Assume that the labels with 0 samples have 1 sample
    # to avoid a divide by zero error
    # the effect of this assumption is quite negligible
    new_counts = np.ones(shape=(26,))
    print(new_counts)
    res = {new_labels[i]: new_counts[i] for i in range(len(new_labels))}
    for i in range(len(labels)):
        res[labels[i]] = counts[i]
    return res

# Now 27 labels
HARmodel = HAR_model_wrapper(adjacency_matrix=adjacency_matrix,
                             timestep=120, node_num=4, feature_num=3, num_class_HAR=18)


def train_model(model: HAR_model_wrapper, X_train: np.ndarray, X_test: np.ndarray,
                Y_train: np.ndarray, Y_test: np.ndarray):
    AdjNorm = utils.MakeGraph(model.adjacency_matrix)
    graphtrain = utils.my_combine(AdjNorm, X_train)
    graphtest = utils.my_combine(AdjNorm, X_test)
    # print("Shape of X train :", X_train.shape)
    # print("Shape of Y train before one-hot encoding: ", Y_train.shape)
    class_counts = np.unique(Y_train, return_counts=True)
    #class_counts = add_missing_labels(class_counts)
    print("Class counts: ", class_counts)
    # One hot encoding
    Y_train = to_categorical(Y_train, num_classes=model.num_classes)
    Y_test = to_categorical(Y_test, num_classes=model.num_classes)
    # print("Shape of categorically encoded Y_train: ", Y_train.shape)
    # print("Shape of categorically encoded Y_test: ", Y_test.shape)
    # Beta = 0.9999 produces a really small loss
    model.model.compile(optimizer=Adam(learning_rate=5e-4, decay=1e-5),
                  loss={
                        # 'HARout': 'categorical_crossentropy'
                        'HARout': utils.focal_loss(weights = utils.class_balance_weights(0.30,
                                     class_counts[1]),
                                     gamma=5, num_class=model.num_classes)
                        },
                  loss_weights={'HARout': 1.},
                  metrics=['categorical_accuracy'])

    history = model.model.fit(x=graphtrain,
              y=Y_train,
              batch_size=150,
              epochs=100,
              #callbacks=utils.build_callbacks('Model', str(valid_patient)),
              validation_data=(graphtest, Y_test)
              )
    plt.plot(history.history['loss'])
    plt.plot(history.history['val_loss'])
    plt.title('Loss over training epochs')
    plt.ylabel('Loss')
    plt.xlabel('epoch')
    plt.legend(['train', 'test'], loc='upper left')
    plt.show()
    model.model.save("Models/GC_LSTM_HAR")
    return model.model

train = input("Train model? Yes/no")
if train=="Yes":
    model = train_model(HARmodel, X_train, X_test, Y_train, Y_test)
else:
    print("Loading model…")
    model = keras.models.load_model("Models/GC_LSTM_HAR")
AdjNorm = utils.MakeGraph(HARmodel.adjacency_matrix)
graphtest = utils.my_combine(AdjNorm, X_test)
print("Y test before categorical encoding: ", Y_test.shape)
predictions = model.predict(graphtest)
print("Shape of predictions: ", predictions.shape)
print("First predictions: ", predictions[0])
# Do these numbers actually sum to 1?
for i in range(predictions.shape[0]):
    print("Sum: ", np.sum(predictions[0]))
    break

#Pretty much. So pick the most likely class
def zeros_and_ones(arr):
    to_return = np.zeros(shape=arr.shape[0])
    for i in range(arr.shape[0]):
        # print("Index of biggest number: ", np.argmax(arr[i]))
        to_return[i] = np.argmax(arr[i])
    return to_return

# Transform predictions back to original shape
predictions = zeros_and_ones(predictions)
# Save results
results = {"F1 score": f1_score(Y_test, predictions, average='weighted'),
           "Accuracy": accuracy_score(Y_test, predictions),
           "Precision": precision_score(Y_test, predictions, average='weighted'),
           "Recall": recall_score(Y_test, predictions, average='weighted'),
           "Confusion matrix": confusion_matrix(Y_test, predictions, labels=np.array(list(range(1, 20))))}
print("F1 score ", f1_score(Y_test, predictions, average='weighted'))
print("Accuracy ", accuracy_score(Y_test, predictions))
print("Precision ", precision_score(Y_test, predictions, average='weighted'))
print("Recall ", recall_score(Y_test, predictions, average='weighted'))
name = input("Please name this experiment")
class NumpyEncoder(json.JSONEncoder):
    def default(self, obj):
        if isinstance(obj, np.ndarray):
            return obj.tolist()
        return json.JSONEncoder.default(self, obj)
json.dump(results, open("Results/Experiment_" + name, "w"), cls=NumpyEncoder)

Adjacency matrix:  [[0. 1. 0. 0.]
 [1. 0. 1. 1.]
 [0. 1. 0. 1.]
 [0. 1. 1. 0.]]
Classes before new encoding  [ 1.  2.  3.  4.  5.  6.  7.  9. 11. 14. 17. 18. 20. 21. 22. 23. 24. 25.
 26. 27.]
Classes after new encoding  [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]
Classes in Y_train:  [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.]
Timestep:  120 Body num:  4 Num classes HAR:  18
HARextend shape:  (None, 120, 4, 18)
HAR temporal output1 shape:  (None, 18)
PDB temporal output1 shape  (None, 2)
Loading model…
Y test before categorical encoding:  (1623, 1)
51/51 [==============================] - 2s 23ms/step


/home/alex/gits/venv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1334: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/alex/gits/venv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1334: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/alex/gits/venv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1334: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/alex/gits/venv/lib/python3.10/site-packages/sklearn/metrics/_classification

Shape of predictions:  (1623, 27)
First predictions:  [1.3189878e-01 2.0279247e-02 7.7285126e-02 1.6469483e-03 1.8222999e-02
 3.0453061e-03 5.0529609e-03 2.4746808e-07 8.1609719e-02 1.3487083e-07
 1.3357607e-07 2.1384147e-07 1.3300468e-07 4.0748292e-03 1.0718756e-07
 1.2955924e-07 1.8027338e-03 6.8514131e-04 2.0005479e-07 1.0837258e-07
 2.5172359e-01 4.2062355e-03 3.7324810e-04 3.8662949e-01 4.6408945e-03
 2.6855671e-03 4.1358219e-03]
Sum:  1.0
F1 score  0.06675616186757685
Accuracy  0.07208872458410351
Precision  0.06258700641983697
Recall  0.07208872458410351
